name: mercuryhealth-web-ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1 
     - name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v3
       with: 
        dotnet-version: '5.0'
     - run: dotnet build -c Release
     - run: dotnet test -c Release
     - run: dotnet publish -c Release -o mercuryhealth-web 
